#ddev-generated
services:
  bref:
    build:
      context: ./craft-cloud
      dockerfile: bref.Dockerfile
    container_name: ddev-${DDEV_PROJECT}-bref
    expose:
      - "8000"
    env_file:
      - ./craft-cloud/.env.static
    environment:
      HANDLER: ${DDEV_DOCROOT}/index.php
      DOCUMENT_ROOT: ${DDEV_DOCROOT}
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: "8000:8000"
      HTTPS_EXPOSE: "8081:8000"
      PHP_IDE_CONFIG: serverName=bref
      CRAFT_CLOUD_S3_ENDPOINT: http://minio.${DDEV_PROJECT}.orb.local:10101
    external_links:
      - ddev-router:${DDEV_PROJECT}.ddev.site
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - .:/mnt/ddev_config
      - ./craft-cloud/php:/var/task/php:ro
      - ./craft-cloud/config/cloud.php:/var/task/config/cloud.php:ro
      - ${DDEV_APPROOT}:/var/task:ro
