#ddev-generated
# MinIO addon for DDEV - Base file
services:
  minio:
    container_name: ddev-${DDEV_SITENAME}-minio
    image: minio/minio:latest
    hostname: ddev-${DDEV_SITENAME}-minio
    environment:
      MINIO_VOLUMES: "/data"
      MINIO_ROOT_USER: ddevminio
      MINIO_ROOT_PASSWORD: ddevminio
    command: >
      server
      --console-address
      :9090
      --address
      :10101
    volumes:
      - "minio:/data"
      - ".:/mnt/ddev_config"
      - ddev-global-cache:/mnt/ddev-global-cache
      - "./craft-cloud/minio/mc-config.json:/root/.mc/config.json"
    expose:
      - "9000"
      - "10101"
    networks:
      - default
      - ddev_default
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1024M"
        reservations:
          cpus: "1"
          memory: "512M"
    restart: "no"
    healthcheck:
      interval: 120s
      timeout: 2s
      retries: 1

volumes:
  minio:
    name: ddev-${DDEV_SITENAME}-minio
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
